Embedding Images and Video
leolpaz/YoutubePlayerPageClone pull request #3
Opened 2020-10-21 21:14 UTC by leolpaz

We made a clone of the youtube player page, it has a functional video, buttons, and interactive icons. The page works best on a 1366x768 resolution and using the firefox browser, assets might look out of place using other browsers or resolutions. It has mock suggestions showing video name and views, and a mock section for commentaries. 

The focus of this branch was to make everything fit in their right places, along with a functional youtube video player.

2020-10-21 21:38 UTC, jubaan requested changes
# This review follows the required changes in PR #2 

# Status: Changes Required :recycle: 

## :wave: :wave: Hello @leolpaz and @gasb150  . Thanks for submitting you project!

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [x] The project has a conflict that must be resolved
![image](https://user-images.githubusercontent.com/25774518/96790157-eebb5a80-13bb-11eb-80c7-924e8082a842.png)

- [x] The extra space haven't been removed

> * [x]  Please move this down and remove extra space
> 
> **clone**
> 
> ![chrome-capture (5)](https://user-images.githubusercontent.com/58504655/96770867-585a5980-13fa-11eb-80d5-27ece8c44f81.jpg)

- [x] Values of 0 shouldn't have units specified. (this issue still appear on the CSS). See inline

### [Comments] :green_circle: 

- :rotating_light: :rotating_light: :rotating_light: The PR should be the same that has been reviewed before, this is not the first time it has happened, please all corrections should be in the initial PR #1. Don't make this a habbit. :rotating_light: :rotating_light: :rotating_light: 

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-10-21 21:38 UTC, jubaan commented on style.css
> +  margin-left: 0%;
See issue above about the 0 and the units

2020-10-21 23:57 UTC, ElijahTobs requested changes
# Status: Changes Required! :recycle:  
### Good job @leolpaz and @gasb150 . You're almost there :smile: 

## Required Changes :wrench: 
### [Mandatory]

- [ ] Zero CSS values should not carry units.

### [Optional]


- [ ] I think it will be better if you replaced **Author1** and **Author2** (as you have it in your README.md file) with your respective names.
![author1](https://user-images.githubusercontent.com/16058470/96800976-880b6080-13fe-11eb-9518-583108543fe6.png)

#### Implement the changes and submit for another review :wink: 
### Happy Coding :muscle: :man_technologist:

2020-10-21 23:57 UTC, ElijahTobs commented on style.css
> +  margin: 0px;
[Mandatory] Kindly make sure that you don't add units to values of zero

2020-10-22 00:28 UTC, umairarshadbutt approved these changes
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
### The [clone](https://raw.githack.com/leolpaz/YoutubePlayerPageClone/YoutubePage/Index.Html) shows a good understanding of Embedding Images and Video. :100:
##
- The cloned page is rendering as it should and meets all the project specifications.
- The project has a descriptive README.md and is professionally done. Good job with that.
- Pull Request has a meaningful title and a short description.
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @leolpaz and @gasb150! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
**If you have any questions, let me know on slack at any time. I will be happy to help.**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-10-22 00:37 UTC, merged